In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[-0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1094, 0.2967, 0.0102],
        [0.3606, 0.5039, 0.3119],
        [0.2461, 0.5126, 0.1991],
        [0.4319, 0.3390, 0.1008],
        [0.5339, 0.6318, 0.7328]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.2793, -1.5002, -1.5343],
        [-0.1031, -0.6229,  0.6301],
        [ 0.9858, -1.4231,  0.9249],
        [ 0.0497,  0.1808,  0.7695],
        [ 2.5416, -0.6493, -0.5165]])


In [9]:
x.size()

torch.Size([5, 3])

In [10]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.2198, -0.8355, -0.8409],
        [ 0.1682, -0.4022,  1.3090],
        [ 1.0472, -1.3411,  1.7135],
        [ 0.8696,  1.0236,  0.8133],
        [ 3.4833, -0.3682, -0.1002]])


In [11]:
print(torch.add(x, y))

tensor([[ 0.2198, -0.8355, -0.8409],
        [ 0.1682, -0.4022,  1.3090],
        [ 1.0472, -1.3411,  1.7135],
        [ 0.8696,  1.0236,  0.8133],
        [ 3.4833, -0.3682, -0.1002]])


In [13]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.2198, -0.8355, -0.8409],
        [ 0.1682, -0.4022,  1.3090],
        [ 1.0472, -1.3411,  1.7135],
        [ 0.8696,  1.0236,  0.8133],
        [ 3.4833, -0.3682, -0.1002]])


In [16]:
y.add_(x)
print(y)

tensor([[-0.3387, -3.8358, -3.9095],
        [-0.0380, -1.6481,  2.5692],
        [ 3.0187, -4.1872,  3.5632],
        [ 0.9690,  1.3852,  2.3523],
        [ 8.5665, -1.6668, -1.1331]])


In [17]:
print(x[:, 1])

tensor([-1.5002, -0.6229, -1.4231,  0.1808, -0.6493])


In [20]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [22]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.2544])
-0.2543666958808899


In [23]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [24]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [25]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [27]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [28]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!